### ISSUE TITLE
Distribute Tools-Image into Product Images

### ISSUE THREAD

**Issue by Maleware** [stackabletech/docker-images#241] opened 2022-11-03 07:01 UTC
With Issue https://github.com/stackabletech/issues/issues/301 we identified the operators using the tools image.

From this List we are going to distribute those tools into their corresponding product images.

### Operator to modify
 - [x] zookeeper - no change needed
- [x] hdfs - no change needed
- [x] kafka
- [x] nifi
- [x] trino
- [x] druid

**Comment by lfrancke** [comment] 2022-12-07 06:44
The checkboxes are al ticked but the issue is not closed yet.

Is this done?
@Maleware

**Comment by Maleware** [comment] 2022-12-07 11:32
Yes, it waits for review currently

**Comment by lfrancke** [comment] 2022-12-08 19:55
@Maleware  I'm  sorry....what is waiting for Review exactly?

**Comment by Maleware** [comment] 2022-12-09 07:58
This PR https://github.com/stackabletech/docker-images/pull/266/files is belongs to this ticket. @maltesander is doing the product image selection, which is needed to Test the changes. Up to that tests it is done, I think.

**Comment by Maleware** [comment] 2022-12-12 08:10
This one: https://github.com/stackabletech/docker-images/pull/266/files

**Comment by maltesander** [comment] 2022-12-13 15:30
duplicate of https://github.com/stackabletech/docker-images/pull/266. Closing this.

**Closed** 2022-12-13 15:30 UTC
